Repository Therapixel/pacsanini, pull requests merged in 2021-07, with the labels that each got.

#6 Fix dicom time parsing. see #3
  scripts/check_copyright.py
  scripts/export_requirements.sh
  scripts/setup_env.sh
  src/pacsanini/convert.py
  tests/convert_test.py
Labels: bug

#10 Fix linting issues + add github workflow.
  .github/workflows/pr.yaml
  .pre-commit-config.yaml
  src/pacsanini/cli/pipeline.py
  src/pacsanini/config.py
  src/pacsanini/pipeline/orchestra.py
  tests/data/dicom-results/dicom_tags.json
  tests/net/c_echo_test.py
  tests/net/c_move_test.py
  tests/net/conftest.py
  tests/net/storescp_test.py
Labels: enhancement

#7 Added Dockerfile + update docs on installation + docs build mechanism
  .dockerignore
  .readthedocs.yaml
  Dockerfile
  README.md
  docs/user_guide/installation.md
  requirements/requirements_doc.txt
Labels: enhancement

#13 Update dependencies + hooks + docs
  .pre-commit-config.yaml
  Makefile
  README.md
  docs/about/contributing.md
  poetry.lock
  pyproject.toml
  requirements/requirements.txt
  requirements/requirements_dev.txt
  scripts/export_requirements.sh
  scripts/setup_env.sh
Labels: dependencies, documentation, security

#18 Update license
  pyproject.toml
Labels: bug

#21 Fixed project classifiers.
  pyproject.toml
Labels: bug

#26 Add link to PyPI page
  README.md
Labels: documentation

#29 Configured mypy and fixed typing issues
  .dockerignore
  .gitignore
  .pre-commit-config.yaml
  Makefile
  mypy.ini
  poetry.lock
  py.typed
  pyproject.toml
  src/pacsanini/cli/net.py
  src/pacsanini/cli/parse.py
  src/pacsanini/config.py
  src/pacsanini/io/base_parser.py
  src/pacsanini/io/df_parser.py
  src/pacsanini/io/io_parsers.py
  src/pacsanini/net/c_echo.py
  src/pacsanini/parse.py
  src/pacsanini/pipeline/orchestra.py
Labels: enhancement

#28 Added documentation on DCO.
  CONTRIBUTING.md
  docs/about/contributing.md
  docs/about/dco.md
  mkdocs.yml
Labels: documentation

#31 Updated installation docs and write tutorials.
  README.md
  docs/index.md
  docs/user_guide/installation.md
  docs/user_guide/tutorials/finding.md
  docs/user_guide/tutorials/moving.md
  docs/user_guide/tutorials/parsing.md
  mkdocs.yml
Labels: documentation

#33 Added tests for utils module.
  src/pacsanini/utils.py
  tests/utils_test.py
Labels: enhancement

#36 Fix callback for nested tags.
  src/pacsanini/parse.py
  tests/parse_test.py
Labels: bug

#39 Include DICOM path in parsing by default.
  src/pacsanini/cli/parse.py
  src/pacsanini/io/base_parser.py
  src/pacsanini/io/df_parser.py
  src/pacsanini/io/io_parsers.py
  tests/cli/parse_test.py
Labels: bug
